### PR TITLE
Produce Windows packages (3rd attempt)

### PR DESCRIPTION
**Pull request by astrojuanlu**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Quoting from the 2nd attempt:

> Interestingly, the recipe is already working with MSVC 2015. I would like to add some tests before trying to fix the MSVC 2008 error. To avoid creating a Windows-specific makefile, we can use Python to make a cross-platform C test. See this for inspiration:
> 
> https://github.com/conda-forge/glpk-feedstock/blob/master/recipe/setup.py

**Comment by mwcraig** [comment]
I'd suggest turning off the redirect to `/nul` at https://github.com/conda-forge/cspice-feedstock/blob/master/recipe/makeDynamicSpice.bat#L47 so you can see whether there is an error at that stage. The fail right now comes when `cspice.dll` is copied, suggesting it isn't actually being created.

**Comment by astrojuanlu** [comment]
Thanks @mwcraig for chiming in! I'll start from there and see how to fix the rest.

**Comment by astrojuanlu** [comment]
This is the error:

```
derfc_.obj : error LNK2019: unresolved external symbol erfc referenced in function derfc_
erfc_.obj : error LNK2001: unresolved external symbol erfc
derf_.obj : error LNK2019: unresolved external symbol erf referenced in function derf_
erf_.obj : error LNK2001: unresolved external symbol erf
cspice.dll : fatal error LNK1120: 2 unresolved externals
```

The `makeDynamicSpice.bat` script has not been modified:

https://github.com/AndrewAnnex/SpiceyPy/blob/v2.1.2/appveyor/makeDynamicSpice.bat

@AndrewAnnex have you ever tried building SpiceyPy on older Windows versions? Also, just in case @conda-forge/core, is there a way to keep MSVC 2015 and disable MSVC 2008 from builds?

**Comment by astrojuanlu** [comment]
Figured it out:

https://conda-forge.org/docs/buildwin.html#building-for-different-vc-versions

**Comment by astrojuanlu** [comment]
Okay, so at least we have a working build now. This week I will at least try whether spiceypy can find the DLL, and if time permits even add a cross-platform test so this feedstock is more reliable. In any case, I will prioritize having a working solution ASAP.

**Comment by mwcraig** [comment]
FWIW, I wouldn't bother supporting anything that requires compilation on Win/Python<3.5...but you know your user base best!

**Comment by AndrewAnnex** [comment]
@mwcraig I wish we could (purely because of type hints in 3.6) but there are a lot of people stuck on 2.7 based on download statistics, and the code was trivial to make backwards compatible using the six package so for now there is little reason to drop 2.7 support. 

@Juanlu001 I have logic in my appveyor/conda related build steps for the mixed ABI compilation issue you should look at. This will be necessary to support 2.7 and possibly 3.7 and beyond if they change the MSVC versions going forward. I am a little surprised that this isn't trivial to solve with conda-forge as ABI compatibility is a common issue to run into.

**Comment by astrojuanlu** [comment]
@AndrewAnnex do you mean https://github.com/AndrewAnnex/SpiceyPy/blob/master/appveyor/windows_sdk.cmd? I'm not sure what happened here though, it seems some trivial linking problem (missing erf and erfc) but I honestly don't know where to start looking, since the code for both MSVC versions is the same.

**Comment by astrojuanlu** [comment]
@AndrewAnnex do you mean https://github.com/AndrewAnnex/SpiceyPy/blob/master/appveyor/windows_sdk.cmd? I'm not sure what happened here though, it seems some trivial linking problem (missing erf and erfc) but I honestly don't know where to start looking, since the code for both MSVC versions is the same.

**Comment by AndrewAnnex** [comment]
I think that is what was needed there is a global environment call at the top of my appveyor.yml that uses it. It basically does the switch for the 2008 MSVC compiler see 'WINDOWS_SDK_VERSION'.  In the end you will want a cspice dll made for both windows sdk versions. Maybe conda-forge has a config option for this?

**Comment by djsutherland** [comment]
@AndrewAnnex You shouldn't need to do that; `{{ compiler('c') }}` as a requirement _should_ be enough. ([docs](https://conda-forge.org/docs/buildwin.html#building-for-different-vc-versions))

You also shouldn't need `libgcc` as a `run` requirement; the `{{ compiler }}` build requirement automatically includes any needed `run` requirements.

**Comment by astrojuanlu** [comment]
The trick here seems to be that the functions Visual Studio complains about were implemented, according to [this comment I found](https://github.com/ldc-developers/ldc/issues/822#issuecomment-143574095), in VS 2013. In theory, the VS version that produces Python 2 packages is 2008 (`vc9`), but as far as I understand @AndrewAnnex uses VS 12.0 (2013) to link SPICE, and it works:

https://ci.appveyor.com/project/AndrewAnnex/spiceypy/build/job/c5msxbpo2xuoakr7

(By the way, if you find the Visual Studio versioning scheme as sickening as I do, you might like [this table](https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#History))

I conclusion, I won't pursue VS 2008 builds of cspice anymore. Instead, I will try to see if this is enough to have a working spiceypy on Win + Python 2.7.

**Comment by astrojuanlu** [comment]
As a last comment, CSPICE is compiled with VS 2015:

https://naif.jpl.nasa.gov/pub/naif/toolkit//C/PC_Windows_VisualC_64bit/packages/README

**Comment by jakirkham** [comment]
The Visual Studio version requirement set by the Python org for Python 2.7 is Visual Studio 2008. As an organization we have decided we are not comfortable deviating from the Python org’s advice on this matter. The only other option we have been ok with is using MinGW compilers with Python 2.7, which may work for your use case if Python 2.7 is needed. Alternatively not supporting Python 2.7 is also an option.

ref: https://wiki.python.org/moin/WindowsCompilers
ref: https://github.com/conda-forge/conda-forge.github.io/issues/64

**Pull request merged**
