### PR TITLE
fix for windows users and spice 2.3.0 where new hidden cspice functio…

### LINKED ISSUE #305: function 'ckfrot_' not found
I am using Anaconda with python 3.7 and installed spiceypy with conda. I try to import the package and get the error "function 'ckfrot_' not found".

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ronan\Anaconda3\lib\site-packages\spiceypy\__init__.py", line 25, in <module>
    from .spiceypy import *
  File "C:\Users\Ronan\Anaconda3\lib\site-packages\spiceypy\spiceypy.py", line 28, in <module>
    from .utils.libspicehelper import libspice
  File "C:\Users\Ronan\Anaconda3\lib\site-packages\spiceypy\utils\libspicehelper.py", line 99, in <module>
    libspice.ckfrot_.argtypes = [c_int_p, c_double_p, (c_double * 3) * 3, c_int_p, c_int_p]
  File "C:\Users\Ronan\Anaconda3\lib\ctypes\__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Ronan\Anaconda3\lib\ctypes\__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'ckfrot_' not found

I don't want to use this function, its just that the import fails.

### PR DESCRIPTION
**Pull request by AndrewAnnex**
…ns were not added to cspice.def

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

should fix https://github.com/AndrewAnnex/SpiceyPy/issues/305

when we update cspice.def in the spiceypy repository we need to update it here also!

### CODE REVIEW

**Comment by AndrewAnnex** [comment]
@conda-forge-admin, please rerender

**Comment by AndrewAnnex** [comment]
this pr is failing because of a bug in conda-build with a fix in a pr I made https://github.com/conda/conda-build/pull/3773

**Comment by AndrewAnnex** [comment]
okay the mechanism described in the conda-build documentation to rename the downloaded file from `tar.Z` to `tar.z` did not work as expected for osx here... will need to report bug to conda-build repo

**Comment by AndrewAnnex** [comment]
Reverted the last commit as it did not help the situation, https://github.com/conda/conda-build/pull/3773 has been merged in so when a new conda-build is released (and utilized by conda-forge) it should hopefully resolve the issue preventing the builds on this pr from working.

**Comment by AndrewAnnex** [comment]
@conda-forge-admin, please rerender

**Comment by AndrewAnnex** [comment]
fun fact: the last time cspice feedstock was built it was under conda-build 3.18.2 
there should probably be a new build tied to each new release of conda-build so that errors in supporting infrastructure can be discovered earlier

**Comment by astrojuanlu** [comment]
>  there should probably be a new build tied to each new release of conda-build so that errors in supporting infrastructure can be discovered earlier

Good point @AndrewAnnex, we'll have to remember to rerender it more often.

**Comment by AndrewAnnex** [comment]
I think it is failing because I'm not specifying to use the broken labeled 3.18.2 ie '-c conda-forge/label/broken'

**Comment by AndrewAnnex** [comment]
k... I think I exhausted all of my options, I must wait for a new version of conda-build @conda-forge-admin, please rerender

**Comment by AndrewAnnex** [comment]
yay! conda-build 3.8.11 is out! @conda-forge-admin, please rerender

**Comment by AndrewAnnex** [comment]
@conda-forge-admin, please rerender

**Comment by AndrewAnnex** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 FINALLY!!! 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Pull request merged**
