### PR TITLE
MNT: Re-rendered with conda-smithy 3.1.5 and pinning 2018.05.22

### PR DESCRIPTION
**Pull request by astrojuanlu**

### CODE REVIEW

**Comment by astrojuanlu** [comment]
@conda-forge/core I just rerendered this recipe and I'm getting an error only in OS X:

```
Source cache directory is: /Users/travis/miniconda3/conda-bld/src_cache
Downloading source to cache: cspice_f5d48c4b0d.tar.Z
Downloading https://naif.jpl.nasa.gov/pub/naif/misc/toolkit_N0066/C/MacIntel_OSX_AppleC_64bit/packages/cspice.tar.Z
Success
Extracting download
source tree in: /Users/travis/miniconda3/conda-bld/cspice_1528239940167/work
/Users/travis/miniconda3/conda-bld/cspice_1528239940167/work/conda_build.sh: line 59: cd: /Users/travis/miniconda3/conda-bld/cspice_1528239940167/work/lib/: No such file or directory
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2177, in build_tree
    notest=notest,
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1417, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 310, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 290, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/travis/miniconda3/conda-bld/cspice_1528239940167/work/conda_build.sh']' returned non-zero exit status 1.
The command "conda build ./recipe -m ./.ci_support/${CONFIG}.yaml" exited with 1.
```

Any clue what's going on? Thanks in advance!

**Comment by mariusvniekerk** [comment]
I'd recommend you try to add the new compilers.

**Comment by astrojuanlu** [comment]
Thanks @mariusvniekerk, do you think it's related to the error? Also, do you know any example feedstock I can get inspiration from? The documentation here https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html is quite extensive and I'm not sure what to add to `meta.yaml`.

**Comment by mariusvniekerk** [comment]
This is probably a bit more digestable

https://conda-forge.org/docs/meta.html#compilers

**Comment by mariusvniekerk** [comment]
The actual error seems to be around your `build.sh` script.  That seems to be going into a path that does not exist?  You may want to add a `set -e set -x` to that bash script to have a bit more visibility

**Comment by astrojuanlu** [comment]
Thanks, makes sense! I don't know how come this works on Linux then, but I'll see if printing more information helps.

**Comment by astrojuanlu** [comment]
Apparently the extraction is happening in different directories in OS X and Linux:

* Linux: https://circleci.com/gh/conda-forge/cspice-feedstock/8 (Ctrl+F for "cspice.tar.Z")
* OS X: https://travis-ci.org/conda-forge/cspice-feedstock/builds/388832944#L334

**Pull request merged**
